version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: "${MONGODB_URI}"
      DB_NAME: "${DB_NAME-test}"
      JWT_SECRET: "${JWT_SECRET}"
      COOKIE_SECURE: "${COOKIE_SECURE-false}"
    restart: unless-stopped
