version: "3.8"
services:
  web:
    build: .
    container_name: alali-web
    restart: unless-stopped
    ports: ["3000:3000"]              # dein Service hört auf 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      # Passwort- Sonderzeichen URL-encoden (! = %21, @ = %40, etc.)
      MONGODB_URI: "mongodb+srv://alali:Alali1995%21@project4.s8sfdmr.mongodb.net/?retryWrites=true&w=majority&appName=project4"
      DB_NAME: "test"
      JWT_SECRET: "setze_einen_langen_random_string"
      COOKIE_SECURE: "false"          # lokal; Produktion = "true"
    volumes:
      - .:/app
      - /app/node_modules
