import "dotenv/config.js";
import express from "express";
import cookieParser from "cookie-parser";
import cors from "cors";
import helmet from "helmet";
import { connect } from "./db.js";
import authRoutes from "./routes/auth.routes.js";
import cartRoutes from "./routes/cart.routes.js";
import productRoutes from "./routes/product.routes.js";
import imageRoutes from "./routes/images.routes.js";
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_ORIGIN?.split(",") || true, credentials: true }));
app.use(cookieParser());
app.use(express.json({ limit: "1mb" }));
app.use(authRoutes);
app.use(cartRoutes);
app.use(productRoutes);
app.use(imageRoutes);
app.get("/healthz", (_req, res) => res.json({ ok: true }));
const port = Number(process.env.PORT || 8080);
await connect();
app.listen(port, () => console.log(`API on :${port}`));
